site_name: scFactor-Ontology
site_url: https://scfactor-ontology.readthedocs.io/en/latest/
repo_url: https://github.com/mrw2204/scFactor-Ontology
repo_name: mrw2204/scFactor-Ontology

theme:
  name: readthedocs
  features:
    - navigation.tabs
    - navigation.sections
    - content.code.copy
    - search.highlight
    - search.share

docs_dir: docs

nav:
  - Home: index.md
  - Tutorials:
      - scFO Overview + General Workflow: vignette.md
      - Tutorial 1 - Construction: Tutorial_1_Construction.ipynb
      - Tutorial 2 - Visualization: Tutorial_2_Visualization.ipynb
      - Tutorial 3 - Projection: Tutorial_3_Projection.ipynb
      - Tutorial 4 - Spatial: Tutorial_4_Spatial.ipynb
      - Tutorial 5 - scHPF: Tutorial_5_scHPF.ipynb
      - Tutorial 6 - LGG: Tutorial_6_LGG.ipynb
      - Tutorial 6 - Perturbation: Tutorial_7_Perturbation.ipynb
  - API: api.md

plugins:
  - search
  - mkdocs-jupyter:
      execute: false
      ignore_h1_titles: false
      include_source: true
      show_input: true
      no_input: false
  - mkdocstrings:
      handlers:
        python:
          paths:
            - src
          options:
            show_source: false
            show_root_heading: true
            show_root_full_path: false
            show_signature_annotations: true
            heading_level: 3
            docstring_style: numpy
            docstring_section_style: list
            separate_signature: true
            show_symbol_type_heading: false
            show_symbol_type_toc: false
            merge_init_into_class: true

markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.details
  - md_in_html
